In [1]:
import pandas as pd

In [24]:
data=pd.read_csv(r"C:\Users\laksh\Downloads\analysis_id (1) 11(in).csv")

In [25]:
data

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,4996,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,728x90,medianet,...,363.0,0.05828,0.05828,0.05828,0.058280,NaN,NaN,NaN,NaN,NaN
4997,4997,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_22,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,4998,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_27,310x260,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,4999,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_33,728x90,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# data['']

In [27]:
len(data['bidder'].unique())

18

In [28]:
data['prebid_win_count']=data['prebid_win_count'].fillna(0)

In [29]:
data['bidder'].unique()

array(['onemobile', 'rhythmone', 'undertone', ' ', 'pulsepoint',
       'pubmatic', 'triplelift', 'sharethrough', 'ix', 'medianet',
       'appnexus', '33across', 'openx', 'emx_digital', 'rubicon',
       'criteo', 'sovrn', 'teads'], dtype=object)

In [30]:
data=data[['bidder','prebid_win_count','response_count']]

In [33]:
data=data[data['bidder']!=' '].reset_index(drop=True)

In [34]:
data

          bidder  prebid_win_count  response_count
0      onemobile               1.0               4
1      rhythmone               0.0               3
2      undertone               0.0               1
3      rhythmone               0.0               2
4     pulsepoint               0.0               1
...          ...               ...             ...
3785    medianet               1.0               1
3786          ix               0.0               1
3787   onemobile               0.0               1
3788       sovrn               0.0               1
3789    medianet               0.0               1

[3790 rows x 3 columns]

In [36]:
df=data.groupby(['bidder'])[['prebid_win_count','response_count']].sum().reset_index()

In [39]:
df.head(2)

     bidder  prebid_win_count  response_count
0  33across             136.0             886
1  appnexus             175.0             830

In [ ]:
df.col

In [40]:
df['Win %']=round((df['prebid_win_count']/df['response_count'])*100,2)

In [41]:
df.sort_values(by=['Win %'],ascending=False)

          bidder  prebid_win_count  response_count  Win %
16     undertone              52.0             104  50.00
14         teads             323.0             700  46.14
9     pulsepoint              71.0             191  37.17
12  sharethrough             104.0             332  31.33
6      onemobile             759.0            2726  27.84
10     rhythmone             160.0             655  24.43
1       appnexus             175.0             830  21.08
2         criteo             587.0            3181  18.45
0       33across             136.0             886  15.35
3    emx_digital              56.0             393  14.25
8       pubmatic             255.0            2335  10.92
5       medianet             253.0            2556   9.90
7          openx              86.0            1165   7.38
15    triplelift             108.0            1479   7.30
4             ix             184.0            3051   6.03
11       rubicon              33.0             582   5.67
13         sovrn              14.0             358   3.91

### Features to consider:
-bid_range:- if its high, the more chance of winning
-response_count:- the more times he gets a  chance (responded by client), the more chances he would win.
-sum_bid:- higher the sum bid amount, higher the response count and more chances of taking part in a bid.
-min_bid:- the higher the min_bid the higher chances of winning
-avg_bid:- the higher the average bid the more chances of winning
-max_bid:-                                                        ### do i have to consider the correlation part as well

In [ ]:
Part 1: Describe how you would build a logistic regression model to predict the probability of a bid winning (win) based on the other columns. 
What features would you select and why? 
Part 2: Based on the following results from a logistic regression model trained on the dataset, interpret the coefficients: 
bid_amount: Coefficient = 0.8 
time_to_bid: Coefficient = -0.4 
ad_unit_A: Coefficient = 0.3 (reference category: ad_unit_B)

In [42]:
big_amount:- coefficient =0.8
effect:- positive impact.
magnitude:- effects strongly (as greater than 0.5, the higher the value the more it impacts the predicted value)
shows:- the higher amount you bid, the more chance of winning

time_to_bid: Coefficient = -0.4 
effect:- negative impact.
magnitude:- low to mild effect (as less than 0.5 but not too close to zero; the higher the value the more it impacts the predicted value)
shows:- the higher time you take to bid, the less chance to win.

ad_unit_A: Coefficient = 0.3
effect:- positive impact
magnitude:- low positive impact. (as its less than 0.5 and close to 0; the lower the value the less it impacts the predicted value)

SyntaxError: invalid syntax (1937781158.py, line 3)